# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoonDuck' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoonDuck
	#UI&CodeConvention
	pod 'Kingfisher', '~> 7.6.1'
	pod 'SwiftLint'
	pod 'SwiftGen'

	#Networking
	pod 'SwiftyJSON'
  	pod 'Alamofire'


  target 'MoonDuckTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoonDuckUITests' do
    # Pods for testing
  end

end
